AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'test/**/*'
    - 'vendor/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
